### ISSUE TITLE
[Question] Lua<->AST

### ISSUE THREAD

**Issue by GoddHoward** [GGG-KILLER/Loretta#1]
Does Loretta support both ways of conversion from:
Lua->AST
AST->Lua
Thanks for reading.

**Comment by GGG-KILLER** [comment]
Yes, it generates an AST from code such as in [Program.cs](https://github.com/GGG-KILLER/Loretta/blob/master/Loretta.CLI/Program.cs#L139-L163) and you can use the [LuaReconstructor](https://github.com/GGG-KILLER/Loretta/blob/master/Loretta/Reconstructors/LuaReconstructor.cs) to generate code from an AST.

But I must warn you, this parser is buggy and won't work all the time.

**Comment by GGG-KILLER** [comment]
Update to this issue.

Post-rewrite, the way to convert an AST back into code is calling `.ToString()`, `.ToFullString()` or `.WriteTo(TextWriter)` on the `SyntaxNode`.
