### ISSUE TITLE
Compound assignment support.

### ISSUE THREAD

**Issue by op0x59** [GGG-KILLER/Loretta#2]
Not sure if Loretta supports Compound assignment support as I looked over the parser.
Reasons for support:
- Roblox added support for compound assignments.

**Comment by GGG-KILLER** [comment]
Would you be able to provide a code sample of it?

I have never used Roblox Lua.

**Comment by op0x59** [comment]
```lua
local x = 0
x += 1
```
There is also: -=, *=, /=, ^=, %=, and ..=

**Comment by GGG-KILLER** [comment]
Right, I'll add support for it as a new Lua type while I don't make the parser modular enough to be able to implement these as pluggable features.

**Comment by GGG-KILLER** [comment]
Added support for it in ad82019.
