### ISSUE TITLE
Support Decompiling Lua.

### ISSUE THREAD

**Issue by AraHaan** [GGG-KILLER/Loretta#33]
I noticed this supports 5.3, but what about 5.1 or 5.2 as well? Cant those be made supported as well for old games that use old lua 5.1 or 5.2?

Also I have a version of unluac that supports 5.1 and 5.2 which I can help provide too you to help you out (would need it to be available to nuget.org so then I could drop my version of an lua decompiler for this sort of project just because it seems far better.

Likewise the compiler I would need to be able to tell it to compile using 5.1 or 5.2 as well and not just 5.3 (for games like Elsword of Grand Chase). For the game versions they used the normal lua 5.1 compiler but for some reason it supported ellipsis which my decompiler either screws it up or the compiler does. Also the files contain Korean words and so must be made to support compiling and decompiling files encoded in UTF-8 WITH BOM. The normal compiler I got forces me to resave without BOM that might be what screws up the korean letters / the '...' characters inside of them when I use the tool to regenerate the KIM file after the raw lua bytecode is generated.

I plan to eventually make an KimLib in c# for my Els_kom program that could then be responsible for regenerating the KIM file / updating it / reading it but it takes time to do.

I probably *could* theoretically update the lua engine but do not want to chance breaking the entire already fragile setup (even though I personally think it only works due to UB and how dumb their devs were to not care how to properly code to not make it barely operable at all).

**Comment by GGG-KILLER** [comment]
This supports 5.1, 5.2 and 5.3 (except for integers which is being tracked by #26).
Just choose the correct options preset and it'll generate error diagnostics (but still parse it properly) on syntax that isn't valid in that lua version.

This project for now is just a lexer and parser so there is no compilation nor decompilation support and decompilation is not planned.

**Comment by GGG-KILLER** [comment]
If I have misunderstood your request please say something, otherwise I'll be keeping this issue closed as wontfix.

**Comment by AraHaan** [comment]
I think it does make more sense to have the compiler stuff to be paired with decompiler stuff (that could possibly share possible code together).

Also my unluac stuff has integer support so it could give hints for #26 as well (which is located in https://github.com/Elskom/Sdk/ under the UnluacNET folder)

It might also give hints for possibly other missing stuff that this possibly lacks for lua 5.1 and 5.2 as well.

**Comment by GGG-KILLER** [comment]
As I said, this project has no compilation capabilities. It does not produce bytecode, only parses lua code.
Even if I were to add compilation support I still do not want to implement a decompiler as the process of decompiling is much more difficult than compilation and producing user-readable code is very hard.
Also, Roslyn does not include decompilation capabilities either. Visual Studio uses `ICSharpCode.Decompiler` for its decompilation capabilities.
